# Generated by Django 5.1.1 on 2024-09-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_login',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tbl_login',
            name='post',
            field=models.CharField(default='default_post', max_length=50),
        ),
        migrations.AddField(
            model_name='tbl_login',
            name='token',
            field=models.CharField(default='default_post', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_login',
            name='verify_status',
            field=models.CharField(default='default_post', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbl_login',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='tbl_login',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
